version: "2.1"

services:
  addresses:
    container_name: addresses
    build:
      context: ./Addresses
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./Addresses:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5001:5000"
      # <port exposed to world>:<internal port>

  leads:
    container_name: leads
    build:
      context: ./Leads
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./Leads:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5002:5000"

  people:
    container_name: people
    build:
      context: ./People
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./People:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5003:5000"
